version: '3'

services:
  app:
    build: .
    container_name: sistema-llamado-pacientes
    restart: always
    ports:
      - "3005:3000"
    volumes:
      - ./public:/app/public
    environment:
      - NODE_ENV=production
    networks:
      - sistema_pacientes_net

networks:
  sistema_pacientes_net:
    driver: bridge
